#!/bin/sh

\rm *.so
ln -s ../../../c/ccpnmr/analysis/ContourFile.so ContourFile.so
ln -s ../../../c/ccpnmr/analysis/ContourLevels.so ContourLevels.so
ln -s ../../../c/ccpnmr/analysis/ContourStyle.so ContourStyle.so
ln -s ../../../c/ccpnmr/analysis/PeakCluster.so PeakCluster.so
ln -s ../../../c/ccpnmr/analysis/PeakList.so PeakList.so
ln -s ../../../c/ccpnmr/analysis/SliceFile.so SliceFile.so
ln -s ../../../c/ccpnmr/analysis/WinPeakList.so WinPeakList.so
ln -s ../../../c/ccpnmr/clouds/AtomCoordList.so .
ln -s ../../../c/ccpnmr/clouds/Bacus.so .
