# Stub for the SharedBeanService SOAP service (generated by SoapSibyz).
# The real module is generated from a WSDL definition at runtime by SoapSibyz.
# This stub provides just enough API to allow imports to succeed.


class SharedBeanServiceLocator:
    """SOAP service locator stub.

    The real implementation requires a configured WSDL endpoint
    (typically at http://www.w3.org/2001/12/soap).
    """

    def __init__(self, *args, **kwargs):
        pass

    def getSharedBeanService(self):
        raise NotImplementedError(
            "SharedBeanService is a SOAP endpoint and requires a live WSDL configuration"
        )

    def getSharedBeanServicePort(self):
        raise NotImplementedError(
            "SharedBeanService is a SOAP endpoint and requires a live WSDL configuration"
        )
